<?php
//
// plotter manual/documentation - example page.
// https://github.com/MarcusOettinger/plotter
//
// This file contains the common menu in all manual/doc-pages
?>
<div id='cssmenu'>
<ul> 
 <li><a href="manual.html#0">syntax</a></li>
 <li><a href="manual.html#1">constants</a></li>
 <li><a href="manual.html#2">predefined functions</a>
   <ul>
    <li><a href="manual.html#3">basic functions</a></li>
    <li><a href="manual.html#4">trigonometric and hyperbolic functions</a></li>
    <li><a href="manual.html#5">non-differentiable functions</a></li>
    <li><a href="manual.html#6">probability functions and statistics</a></li>
    <li><a href="manual.html#7">special functions</a></li>
    <li><a href="manual.html#8">logic functions</a></li>
    <li><a href="manual.html#9">iterations &amp; fractals</a></li>
    <li><a href="manual.html#10">differential and integral equations</a></li>
   </ul></li>
  <li><a href="manual.html#11">options</a></li>
  <li><a href="manual.html#12">calculate</a></li>
  <li><a href="manual.html#13">load &amp; save</a></li>
  <li><a href="examples.html">examples</a>
  <li><a href="manual.html#14">licensing</a></li>
</ul>
</div>