<?php
//
// 
//
// common menu in all Manual/doc-pages
?>
<ul id="main-menu" class="sm sm-mint"> 
 <li><a href="manual.html#0">syntax</a></li>
 <li><a href="manual.html#1">constants</a></li>
 <li><a href="manual.html#2">predefined functions</a>
   <ul>
    <li><a href="manual.html#3">basic functions</a></li>
    <li><a href="manual.html#4">trigonometric and hyperbolic functions</a></li>
    <li><a href="manual.html#5">non-differentiable functions</a></li>
    <li><a href="manual.html#6">probability functions and statistics</a></li>
    <li><a href="manual.html#7">special functions</a></li>
    <li><a href="manual.html#8">logic functions</a></li>
    <li><a href="manual.html#9">iterations &amp; fractals</a></li>
    <li><a href="manual.html#10">differential and integral equations</a></li>
   </ul></li>
  <li><a href="manual.html#11">options</a></li>
  <li><a href="examples.html">examples</a>
  <li><a href="manual.html#14">licensing</a></li>
  </li>
</ul>