<?php
// 06/2020
// plotter manual/documentation and example page.
// https://github.com/MarcusOettinger/plotter
//
// This file contains the common menu in all manual/doc-pages
?>
<div class="cssmenu">
 <a href="manual.html#0">syntax</a>
 <a href="manual.html#1">constants</a>
 <div class="subnav">
    <button class="subnavbtn">functions <i class="fa fa-caret-down"></i></button>
    <div class="subnav-content">
    <a href="manual.html#3">basic functions</a>
    <a href="manual.html#4">trigonometric and hyperbolic</a>
    <a href="manual.html#5">non-differentiable functions</a>
    <a href="manual.html#6">probability and statistics</a>
    <a href="manual.html#7">special functions</a>
    <a href="manual.html#8">logic </a>
    <a href="manual.html#9">iterations &amp; fractals</a>
    <a href="manual.html#10">differential and integral equations</a>
    </div>
  </div>
  <a href="manual.html#11">options</a>
  <a href="manual.html#12">calculate</a>
  <a href="manual.html#13">load &amp; save</a>
  <a href="examples.html">examples</a>
  <a href="manual.html#14">licensing</a>
</div>
